/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedOrcamentosIndexRouteImport } from './routes/_authenticated/orcamentos.index'
import { Route as AuthenticatedOrcamentosNovoRouteImport } from './routes/_authenticated/orcamentos.novo'
import { Route as AuthenticatedOrcamentosIdRouteImport } from './routes/_authenticated/orcamentos.$id'
import { Route as AuthenticatedOrcamentosIdPreviewRouteImport } from './routes/_authenticated/orcamentos.$id.preview'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosIndexRoute =
  AuthenticatedOrcamentosIndexRouteImport.update({
    id: '/orcamentos/',
    path: '/orcamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosNovoRoute =
  AuthenticatedOrcamentosNovoRouteImport.update({
    id: '/orcamentos/novo',
    path: '/orcamentos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosIdRoute =
  AuthenticatedOrcamentosIdRouteImport.update({
    id: '/orcamentos/$id',
    path: '/orcamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosIdPreviewRoute =
  AuthenticatedOrcamentosIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedOrcamentosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRouteWithChildren
  '/orcamentos/novo': typeof AuthenticatedOrcamentosNovoRoute
  '/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/orcamentos/$id/preview': typeof AuthenticatedOrcamentosIdPreviewRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/': typeof AuthenticatedIndexRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRouteWithChildren
  '/orcamentos/novo': typeof AuthenticatedOrcamentosNovoRoute
  '/orcamentos': typeof AuthenticatedOrcamentosIndexRoute
  '/orcamentos/$id/preview': typeof AuthenticatedOrcamentosIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/orcamentos/$id': typeof AuthenticatedOrcamentosIdRouteWithChildren
  '/_authenticated/orcamentos/novo': typeof AuthenticatedOrcamentosNovoRoute
  '/_authenticated/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/_authenticated/orcamentos/$id/preview': typeof AuthenticatedOrcamentosIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/configuracoes'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/orcamentos/'
    | '/orcamentos/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/clientes'
    | '/configuracoes'
    | '/'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/orcamentos'
    | '/orcamentos/$id/preview'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/'
    | '/_authenticated/orcamentos/$id'
    | '/_authenticated/orcamentos/novo'
    | '/_authenticated/orcamentos/'
    | '/_authenticated/orcamentos/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/': {
      id: '/_authenticated/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AuthenticatedOrcamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/novo': {
      id: '/_authenticated/orcamentos/novo'
      path: '/orcamentos/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof AuthenticatedOrcamentosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/$id': {
      id: '/_authenticated/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof AuthenticatedOrcamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/$id/preview': {
      id: '/_authenticated/orcamentos/$id/preview'
      path: '/preview'
      fullPath: '/orcamentos/$id/preview'
      preLoaderRoute: typeof AuthenticatedOrcamentosIdPreviewRouteImport
      parentRoute: typeof AuthenticatedOrcamentosIdRoute
    }
  }
}

interface AuthenticatedOrcamentosIdRouteChildren {
  AuthenticatedOrcamentosIdPreviewRoute: typeof AuthenticatedOrcamentosIdPreviewRoute
}

const AuthenticatedOrcamentosIdRouteChildren: AuthenticatedOrcamentosIdRouteChildren =
  {
    AuthenticatedOrcamentosIdPreviewRoute:
      AuthenticatedOrcamentosIdPreviewRoute,
  }

const AuthenticatedOrcamentosIdRouteWithChildren =
  AuthenticatedOrcamentosIdRoute._addFileChildren(
    AuthenticatedOrcamentosIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrcamentosIdRoute: typeof AuthenticatedOrcamentosIdRouteWithChildren
  AuthenticatedOrcamentosNovoRoute: typeof AuthenticatedOrcamentosNovoRoute
  AuthenticatedOrcamentosIndexRoute: typeof AuthenticatedOrcamentosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrcamentosIdRoute: AuthenticatedOrcamentosIdRouteWithChildren,
  AuthenticatedOrcamentosNovoRoute: AuthenticatedOrcamentosNovoRoute,
  AuthenticatedOrcamentosIndexRoute: AuthenticatedOrcamentosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
